name: mlops-example-tensorflow-regression
on: [push]
jobs:  
  run:    
    runs-on: [ubuntu-latest]    
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1    
    steps:
      - uses: actions/checkout@v3  
      - name: 'train my model'
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  
          pip install -r requirements.txt
          python model.py  

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          cml comment create --token $REPO_TOKEN --file report.md
