name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python environment'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Train the model'
        run: |
          python model.py
      - name: 'Generate and publish report'
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml comment create report.md
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
