name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Train the model
        run: python model.py
      
      - name: Create and send CML report
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          cml comment create --token $REPO_TOKEN --file report.md --target "pr"
